server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: on_param
    include-path: always
    include-stacktrace: on_param
    include-binding-errors: on_param
    include-exception: false
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework.security: trace
    org.springframework.transaction: trace
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: debug
    org.springframework.web: INFO
    org.springframework.security.oauth2: trace
    org.springframework.boot.autoconfigure: INFO

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: spring-rest-api
  main:
    banner-mode: off
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    generate-unique-name: false
    driver-class-name: org.h2.Driver
  security:
  #    oauth2:
  #      client:
  #        registration:
  #          login-client:
  #            provider: spring
  #            client-id: login-client
  #            client-secret: "{noop}secret"
  #            client-authentication-method: client_secret_basic
  #            authorization-grant-type: authorization_code
  #            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/login-client
  #            scope: openid,profile
  #            client-name: Spring
  #          google:
  #            client-id: your-app-client-id
  #            client-secret: your-app-client-secret
  #          github:
  #            client-id: your-app-client-id
  #            client-secret: your-app-client-secret
  #          facebook:
  #            client-id: your-app-client-id
  #            client-secret: your-app-client-secret
  #        provider:
  #          spring:
  #            authorization-uri: http://localhost:8080/oauth2/authorize
  #            token-uri: http://localhost:8080/oauth2/token
  #            jwk-set-uri: http://localhost:8080/oauth2/jwks
  docker:
    compose:
      enabled: false

management:
  health:
    redis:
      enabled: false